[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "simple_kv"
dynamic = ["version"]
dependencies = ["litestar", "bcrypt", "loguru"]

[tool.hatch.version]
source = "vcs"
